### ISSUE TITLE
does pyshacl work for json-ld 1.1? 

### ISSUE THREAD

**Issue by sanuann** [RDFLib/pySHACL#39]
if there is `@version: 1.1` mentioned in the context of a jsonld data graph, pySHACL throws error :
"TypeError: argument of type 'float' is not iterable."

How do I validate data graphs which are written in json-ld 1.1 version?

I also posted this here: https://webmasters.stackexchange.com/questions/127215/how-to-validate-data-graph-expressed-in-json-ld-version-1-1-with-shacl

Can somebody here help? @ashleysommer ?

**Comment by ashleysommer** [comment]
Hi @sanuann 
Thanks for bringing this to my attention.

PySHACL is limited to the file formats supported by the RDFLib parsers.
It appears the RDFLib-jsonld parser does _not_ support json-ld 1.1.
I will check with the upstream authors if there are any plans of adding that feature.

**Comment by sanuann** [comment]
@ashleysommer thanks for looking into it. 

I also posted a comment here: https://github.com/RDFLib/rdflib-jsonld/issues/54#issuecomment-575340394 to which some fix was committed. I made similar change(use `str` instead of `unicode` as suggested in the fix) in my installed version of rdflib-jsonld and it seems to solve the problem I faced.

**Comment by ashleysommer** [comment]
@sanuann 
Good news. I've been selected to be a co-maintainer and co-release-manager for the rdflib-jsonld project. We are looking to do a bugfix release as soon as possible to fix the `unicode` issue, and after than work to put out a new major release with full JSON-LD v1.1 parsing support.

**Comment by nicholascar** [comment]
rdflib-jsonld now has a new release, 0.5.0, to work with rdflib 5.0.0. 

The rdflib-jsonld 0.5.0 release still doesn't contain all the recently added JSON-LD 1.1 updates which are in a branch (see https://github.com/RDFLib/rdflib-jsonld/tree/feature/json-ld-1.1) but they should be in a 0.6.0 release shortly, As soon as that's come through, pySHACL should be able to be updated.

Any help with rdflib-jsonld appreciated!

**Comment by ashleysommer** [comment]
This can be closed now. RDFLib v6 has JSON-LD v1.1 support baked in.
