### ISSUE TITLE
Command line option --abort has no effect

### ISSUE THREAD

**Issue by tjroamer** [RDFLib/pySHACL#75]
I tried to use "--abort" in the command line, but I still got all the errors printed out. I am expecting that the program would quit after the first error is encountered. I went through the source code, and it seems that the function `abort_on_error` is not implemented. Is this a bug?

**Comment by ashleysommer** [comment]
Hi @tjroamer 
I'm aware there are problems with the --abort feature. That goes for the command line option and for the library config option.

It's one of those features that was on the original roadmap in the early days of PySHACL, it's documented but was never implemented properly. We found very few people use the feature anyway.

We should either fix it so it works as expected, or remove the feature entirely.

**Comment by ashleysommer** [comment]
Hi @tjroamer 
This feature is fixed now.
The option is renamed to `abort_on_first`, and can still be accessed by `--abort` on the command line.
Let us know if it fixes the problem for you.

Resolved by https://github.com/RDFLib/pySHACL/commit/72027edb35d417ab1335b172df1c285b60c6c381

**Comment by tjroamer** [comment]
Thanks. I upgraded my pyshacl version to 0.14.5, but the problem is still there. I always got all errors from my data files, even if `--abort` is used. I tried to use `test/resources/dash_tests/core/complex/personexample.test.ttl` to reproduce the error, but found the results are not deterministic. Two runs generated different results.

The first run:

```
python -m pyshacl --abort test/resources/dash_tests/core/complex/personexample.test.ttl
RDFLib Version: 5.0.0
Validation Report
Conforms: False
Results (3):
Constraint Violation in MaxCountConstraintComponent (http://www.w3.org/ns/shacl#MaxCountConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:datatype xsd:string ; sh:maxCount Literal("1", datatype=xsd:integer) ; sh:message Literal("SSN must be 3 digits - 2 digits - 4 digits.") ; sh:path ex:ssn ; sh:pattern Literal("^\d{3}-\d{2}-\d{4}$") ]
        Focus Node: ex:Bob
        Result Path: ex:ssn
        Message: SSN must be 3 digits - 2 digits - 4 digits.
Constraint Violation in PatternConstraintComponent (http://www.w3.org/ns/shacl#PatternConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:datatype xsd:string ; sh:maxCount Literal("1", datatype=xsd:integer) ; sh:message Literal("SSN must be 3 digits - 2 digits - 4 digits.") ; sh:path ex:ssn ; sh:pattern Literal("^\d{3}-\d{2}-\d{4}$") ]
        Focus Node: ex:Alice
        Value Node: Literal("987-65-432A")
        Result Path: ex:ssn
        Message: SSN must be 3 digits - 2 digits - 4 digits.
Constraint Violation in ClassConstraintComponent (http://www.w3.org/ns/shacl#ClassConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:class ex:Company ; sh:nodeKind sh:IRI ; sh:path ex:worksFor ]
        Focus Node: ex:Calvin
        Value Node: ex:UntypedCompany
        Result Path: ex:worksFor
        Message: Value does not have class ex:Company
```

Then I ran it again, this time it is OK:

```
python -m pyshacl --abort test/resources/dash_tests/core/complex/personexample.test.ttl
RDFLib Version: 5.0.0
Validation Report
Conforms: False
Results (1):
Constraint Violation in ClosedConstraintComponent (http://www.w3.org/ns/shacl#ClosedConstraintComponent):
        Severity: sh:Violation
        Source Shape: ex:PersonShape
        Focus Node: ex:Calvin
        Value Node: Literal("1999-09-09", datatype=xsd:date)
        Result Path: ex:birthDate
        Message: Node ex:Calvin is closed. It cannot have value: Literal("1999-09-09", datatype=xsd:date)
```

Could you please check it again?

**Comment by ashleysommer** [comment]
Hi @tjroamer 
Thanks for testing.
The non-determinism comes from the fact that nodes in a graph are unordered. Therefore, the order in which Shapes in the ShapeGraph are executed is non-deterministic, and the order which the individual Constrains within that Shape are evaluated is also non-deterministic.

One thing I left out of my previous comment, is that the `--abort` mechanism is implemented on a per-constraint _kind_ basis. 
The `ex:PersonShape` has two different constraint _kinds_. There are `sh:property` and `sh:closed`. There are three values for `sh:property` on `ex:PersonShape`, and one value for `sh:closed`. 

If the `sh:closed` constraint kind is evaluated first, it emits one validation violation, then due to the `--abort` flag, it skips checking `sh:property` and exits the validator.
If the `sh:property` constraint kind is evaluated first, it validates _all three_ values for `sh:property` at the same time. It emits the validation results for that (in that case, three violations), then due to the  `--abort` flag, it skips checking `sh:closed` and exits the validator.

I can see that it would be unintuitive that the validator emits three validation results when you've asked for it to abort after the first one. But when executing a constraint with multiple value objects (like in the case of `sh:property`) there is no mechanism in place for the constraint to execute just one of those.

I could put in place a filter, for in the case that multiple validation violations come back from a constraint evaluation, if the validator is in abort mode, emit just one of those and discard the others. That however would too be non-deterministic, and a different violation would be emitted each time.

**Comment by ashleysommer** [comment]
@tjroamer 
I've been thinking about this a bit more. There are certain constraint kinds that are referred to in the SHACL Spec as "[shape-expecting](https://www.w3.org/TR/shacl/#dfn-shape-expecting-constraint-parameters)". These are constraints like `sh:node` and `sh:property` which are expected to point to another shape. Eg, values for `sh:property` have a path and are themselves a `PropertyShape`, and values for `sh:node` are themselves other nodes.
So I think it might make sense for these special kinds of Constraint types to have special abort handling baked in, to pass the abort option down to the child shape.

Another thing to consider is the case of "shape-expecting and list-taking" constraint types, like `sh:and` or `sh:or`. Their value object will have a list of shapes that each need to be evaluated in order to determine a result, but they themselves emit only one violation.

**Comment by tjroamer** [comment]
Thanks for the investigation. Now I understand the cause of the behavior. My use case of using `--abort` is that I have a data graph of several Gigabytes. Each time when I tried to validate this data graph, I got thousands of errors and it took sevaral minutes to produce the errors. If I look into the results, there are only less than 10 error kinds. 

There might be serveral use cases, IMHO:

1) abort the validation process for the first error: with this behavior, the user will be able to immediately get the feedback whether the data graph is valid without waiting several minutes. He can then fix one by one if he wants. A CI/CD pipeline could benefit from this feature to just give a passed/failed response. I believe, the non-deterministic behavior should be acceptable.

2) shape kind-based abortion: this is specific to the case that I have. For example, I have thousands of data instances and a property is missing on all of these data instances. For that property shape, I may just want to see one error, instead of thousands of errors of same kind. Another scenario, if I have only 10 shapes defined, and I have a huge database, I can see that 8 of 10 shapes have been violated in my database. So, I want to see 8 errors, without waiting several minutes. At the moment, I am writing my own SPARQL to filter out the generated results to clean up the generated results. The rationale is: normally the data graph will be populated automatically by scripts. If we have this info, we could just tune the script a bit to let all data instances pass the validation. Here, the results should be independent of the order of evaluation, the order of the results might be still non-deterministic, though.

I am not sure whether the above two use uses can be easily implemented. I understand it would be very complicated if "shape-expecting and list-taking" needs to be considered. I was also not thinking that far.

I appreciate your effort. The library is quite nice. :-)

**Comment by ashleysommer** [comment]
@tjroamer 
I see what you mean.
First some mechanics, this is a very high level pseudo-code represenation of how pyshacl evaluates a datagraph.
```
1) For each Shape $s in the Shapes graph:
    2) Find all nodes from the datagraph that this shape applies to (using targeting rules) These are called "focus nodes"
    3) For each focus node $f:
        4) determine corresponding value nodes ($v) (ie, follow the path and get the value if the shape is a PropertyShape)
    5) For each constraint component type $cc on in shape $s:
        6) For each constraint value (object) $cv on each instance of $cc on shape $s:
            7) For each focus node $f from step 3:
                8) For each value node $v for $f from step 4:
                    9) result = Evaluate $f and $v against $cv  <-- this is a single constraint evaluation against a single data node
```
For now the abort mechanism works at the level corresponding to `5)` in the above snippet. That is because steps 1->5 are executed by the validator routine, and steps 6->9 are handled in custom logic specific to each Constraint Component.
It is much easier to implement the abort on first failure feature at that level, in one place in the code, rather than on the component level, I'd need to add abort logic into 30 different places.

My proposal in my second comment above was to potentially try to move the abort mechanism to step `6)`, only for _some_ kinds of components (the shape-expecting and non-list-taking components). That is still quite a bit of work (I'm scoping it out now).

I fear however that what you really need for your usecase is abort-on-first-failure logic at the focus-node  or value-node level, corresponding to steps `7)` or `8)` in the above snippet. I don' think that is possible without a major re-write of the PySHACL execution engine. Maybe in v2.0.

I agree with what you said about there being several different use-cases for this feature, different users will expect it to behave differently. That's why I went for the easiest-to-implement low-hanging-fruit version in my recent release, it is _an_ implementation, and might be what some users are wanting.

**Comment by tjroamer** [comment]
Thanks for the detailed explanation. Now the behavior is clear for me. Yes, to cover the use cases mentioned in my previous comment, the abortion at 8) is required. The two use cases need however different implementation mechanisms. The first one is complete abortion, and the second one is abortion at the current shape, but continue with other shapes. 

I can understand the big effort of implementing the mentioned behavior based on the current architecture. In my view, the major benefit of abortion is the validation performance, because one could also use an external program (e.g. grep or SPARQL) to filter the results. However, if the performance is not an issue, I don't think abort is a mandatory function, and generating all errors may be just fine.

BTW, do you see any chance to have a deterministic evaluation results, e.g. by using the order in the file? Or it is not possible at all to predict the order? If yes, would it be possible to have an option to use the order appeared in the file? The point is: each time I got a different set of results, even if they are the same. It is hard to do diff for them. 

Many thanks for your effort.
